#!/usr/bin/env python3

import os
import sys

from termcolor import colored
from analyzer import Analyzer
from helpers import get_user_timeline

def main():

    # ensure proper usage
    if len(sys.argv) != 2:

        sys.exit("Proper Usage: ./tweets @username")

    list_of_tweets = get_user_timeline(sys.argv[1], 50)

    if list_of_tweets is None:

        sys.exit("Private/incorrect username.")

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    for tweet in list_of_tweets:

        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored("{} {}".format(score, tweet), "green"))
        elif score < 0.0:
            print(colored("{} {}".format(score, tweet), "red"))
        else:
            print(colored("{} {}".format(score, tweet), "yellow"))



if __name__ == "__main__":
    main()